'''
Script to compare forward optical flow from PNG and NPZ sources for consistency.
Compares flow from:
1. PNG files (original TartanAir format)
2. NPZ files (generated by customize_flow)
'''

import os
import numpy as np
import cv2
from tartanair.reader import TartanAirImageReader
from pathlib import Path
from matplotlib.colors import hsv_to_rgb

try:
    import rerun as rr
    RERUN_AVAILABLE = True
except ImportError:
    RERUN_AVAILABLE = False
    print("Warning: rerun not available. Install with 'pip install rerun-sdk' for visualization support.")


def visualize_flow(flow, max_flow=100.0):
    """Convert optical flow data to a color image for visualization."""
    flow_magnitude = np.linalg.norm(flow, axis=-1)
    flow_angle = np.arctan2(flow[:, :, 1], flow[:, :, 0])  # angle in radians

    # Normalize magnitude to [0, 1]
    normalized_magnitude = np.clip(flow_magnitude / max_flow, 0, 1)
    # Map angle to [0, 1]
    normalized_angle = (flow_angle + np.pi) / (2 * np.pi)

    # HSV to RGB conversion
    hsv_image = np.zeros((*flow.shape[:2], 3), dtype=np.float32)
    hsv_image[:, :, 0] = normalized_angle  # Hue
    hsv_image[:, :, 1] = normalized_magnitude  # Saturation
    hsv_image[:, :, 2] = 1.0  # Value

    rgb_image = (hsv_to_rgb(hsv_image) * 255).astype(np.uint8)
    return rgb_image

def compare_flow_sources(png_dir, npz_dir, num_samples=10, verbose=True, visualize_rerun=False, rerun_addr="rerun://100.89.23.40:9876", rgb_dir=None):
    """
    Compare forward flow from PNG and NPZ sources.

    Args:
        png_dir: Directory containing PNG flow files (format: XXXXXX_YYYYYY_flow.png)
        npz_dir: Directory containing NPZ flow files (format: XXXXXX_YYYYYY_lcam_front_flow.npz)
        num_samples: Number of files to compare (None = all files)
        verbose: Print detailed comparison for each file
        visualize_rerun: If True, stream visualizations to rerun
        rerun_addr: Rerun server address (default: "100.89.23.40:9876")
        rgb_dir: Optional directory containing RGB images (format: XXXXXX_lcam_front.png)

    Returns:
        Dictionary with comparison statistics
    """

    # Initialize rerun if requested
    if visualize_rerun:
        if not RERUN_AVAILABLE:
            print("ERROR: rerun-sdk not available. Cannot visualize.")
            visualize_rerun = False
        else:
            rr.init("flow_comparison", spawn=False)
            rr.connect_grpc(rerun_addr)
            print(f"Connected to rerun at {rerun_addr}")

    # Initialize reader
    reader = TartanAirImageReader()

    # Get list of PNG files
    png_files = sorted([f for f in os.listdir(png_dir) if f.endswith('_flow.png')])

    if num_samples is not None:
        # Sample evenly across the sequence
        indices = np.linspace(0, len(png_files)-1, num_samples, dtype=int)
        png_files = [png_files[i] for i in indices]

    print(f"Comparing {len(png_files)} flow files...")
    print(f"PNG directory: {png_dir}")
    print(f"NPZ directory: {npz_dir}")
    print("="*80)

    results = {
        'num_files': len(png_files),
        'max_abs_error': [],
        'mean_abs_error': [],
        'rmse': [],
        'max_relative_error': [],
        'num_pixels_compared': [],
        'mask_agreement': [],
        'mask_png_valid_count': [],
        'mask_npz_valid_count': [],
        'mask_both_valid_count': []
    }

    for png_file in png_files:
        # Construct file paths
        # PNG: 000000_000001_flow.png
        # NPZ: 000000_000001_lcam_front_flow.npz
        frame_prefix = png_file.replace('_flow.png', '')
        npz_file = f"{frame_prefix}_lcam_front_flow.npz"

        png_path = os.path.join(png_dir, png_file)
        npz_path = os.path.join(npz_dir, npz_file)

        if not os.path.exists(npz_path):
            print(f"⚠️  NPZ file not found: {npz_file}")
            continue

        # Read flow from PNG (also load mask separately)
        flow_png = reader.read_flow(png_path, direction="fwd")

        # Load PNG to get the mask
        flow16_png = cv2.imread(png_path, cv2.IMREAD_UNCHANGED)
        mask_png = flow16_png[:, :, 2].astype(np.uint8) if flow16_png is not None else None

        # Read flow from NPZ
        flow_npz = reader.read_flow(npz_path, direction="fwd")

        # Load NPZ to get the mask
        with np.load(npz_path) as data:
            # Use covisible mask (non-occluded) for valid pixels
            mask_npz = data.get('covisible_mask_fwd', None)
            if mask_npz is not None:
                mask_npz = mask_npz[0]  # Remove batch dimension

        # Check shape consistency
        if flow_png.shape != flow_npz.shape:
            print(f"❌ Shape mismatch for {png_file}: PNG {flow_png.shape} vs NPZ {flow_npz.shape}")
            continue

        # Compute differences
        diff = np.abs(flow_png - flow_npz)

        # Create valid masks for both sources
        # PNG mask: 0 = valid, >0 = invalid (1=CROSS_OCC, 10=SELF_OCC, 100=OUT_OF_FOV, 200=OVER_THRESHOLD)
        valid_mask_png = (mask_png == 0)

        # NPZ mask: covisible_mask_fwd where True = valid/non-occluded
        valid_mask_npz = mask_npz.astype(bool) if mask_npz is not None else np.ones_like(mask_png, dtype=bool)

        # Compare masks
        mask_agreement = np.mean(valid_mask_png == valid_mask_npz)
        png_valid_count = valid_mask_png.sum()
        npz_valid_count = valid_mask_npz.sum()
        both_valid_count = (valid_mask_png & valid_mask_npz).sum()

        # Use intersection of both masks for flow comparison
        valid_mask = valid_mask_png & valid_mask_npz

        if valid_mask.sum() == 0:
            print(f"⚠️  No valid pixels in {png_file}")
            continue

        # Compute error metrics on valid pixels
        diff_valid = diff[valid_mask]
        flow_png_valid = flow_png[valid_mask]

        max_abs_err = np.max(diff_valid)
        mean_abs_err = np.mean(diff_valid)
        rmse = np.sqrt(np.mean(diff_valid**2))

        # Compute relative error (avoid division by zero)
        flow_magnitude = np.sqrt(flow_png_valid[:, 0]**2 + flow_png_valid[:, 1]**2)
        diff_magnitude = np.sqrt(diff_valid[:, 0]**2 + diff_valid[:, 1]**2)
        relative_err = diff_magnitude / (flow_magnitude + 1e-6)
        max_relative_err = np.max(relative_err)

        # Store results
        results['max_abs_error'].append(max_abs_err)
        results['mean_abs_error'].append(mean_abs_err)
        results['rmse'].append(rmse)
        results['max_relative_error'].append(max_relative_err)
        results['num_pixels_compared'].append(valid_mask.sum())
        results['mask_agreement'].append(mask_agreement)
        results['mask_png_valid_count'].append(png_valid_count)
        results['mask_npz_valid_count'].append(npz_valid_count)
        results['mask_both_valid_count'].append(both_valid_count)

        # Visualize in rerun if requested
        if visualize_rerun:
            # Extract frame indices for timeline
            frame_idx = int(frame_prefix.split('_')[0])
            rr.set_time("frame", sequence=frame_idx)

            # Visualize RGB image if directory provided
            if rgb_dir is not None:
                rgb_file = f"{frame_prefix.split('_')[0]}_lcam_front.png"
                rgb_path = os.path.join(rgb_dir, rgb_file)
                if os.path.exists(rgb_path):
                    rgb_image = cv2.imread(rgb_path, cv2.IMREAD_COLOR)
                    if rgb_image is not None:
                        # Convert BGR to RGB for proper display
                        rgb_image = cv2.cvtColor(rgb_image, cv2.COLOR_BGR2RGB)
                        rr.log("image_lcam_front", rr.Image(rgb_image))

            # Visualize PNG flow
            flow_png_vis = visualize_flow(flow_png, max_flow=50.0)
            rr.log("comparison/flow_png", rr.Image(flow_png_vis))

            # Visualize NPZ flow
            flow_npz_vis = visualize_flow(flow_npz, max_flow=50.0)
            rr.log("comparison/flow_npz", rr.Image(flow_npz_vis))

            # Visualize flow difference (amplified for visibility)
            flow_diff_vis = visualize_flow(diff, max_flow=5.0)
            rr.log("comparison/flow_diff", rr.Image(flow_diff_vis))

            # Visualize PNG mask as segmentation
            # PNG mask: 0=valid, 1=CROSS_OCC, 10=SELF_OCC, 100=OUT_OF_FOV, 200=OVER_THRESHOLD
            rr.log("comparison/mask_png", rr.SegmentationImage(mask_png.astype(np.uint8)))

            # Visualize NPZ mask as segmentation
            # Convert boolean to 0/1 for visualization
            mask_npz_vis = mask_npz.astype(np.uint8)
            rr.log("comparison/mask_npz", rr.SegmentationImage(mask_npz_vis))

            # Visualize mask disagreement
            # 0 = both agree invalid, 1 = both agree valid, 2 = PNG valid/NPZ invalid, 3 = PNG invalid/NPZ valid
            mask_comparison = np.zeros_like(mask_png, dtype=np.uint8)
            mask_comparison[~valid_mask_png & ~valid_mask_npz] = 0  # Both invalid
            mask_comparison[valid_mask_png & valid_mask_npz] = 1     # Both valid
            mask_comparison[valid_mask_png & ~valid_mask_npz] = 2    # PNG valid, NPZ invalid
            mask_comparison[~valid_mask_png & valid_mask_npz] = 3    # PNG invalid, NPZ valid
            rr.log("comparison/mask_disagreement", rr.SegmentationImage(mask_comparison))

            # Log statistics as scalar
            rr.log("stats/max_abs_error", rr.Scalars(max_abs_err))
            rr.log("stats/mean_abs_error", rr.Scalars(mean_abs_err))
            rr.log("stats/rmse", rr.Scalars(rmse))
            rr.log("stats/mask_agreement", rr.Scalars(mask_agreement))

        if verbose:
            print(f"\n{png_file}:")
            print(f"  Shape: {flow_png.shape}")
            print(f"  Mask Comparison:")
            print(f"    PNG valid pixels: {png_valid_count} ({png_valid_count/valid_mask.size*100:.1f}%)")
            print(f"    NPZ valid pixels: {npz_valid_count} ({npz_valid_count/valid_mask.size*100:.1f}%)")
            print(f"    Both valid (intersection): {both_valid_count} ({both_valid_count/valid_mask.size*100:.1f}%)")
            print(f"    Mask agreement: {mask_agreement*100:.2f}%")
            print(f"  Flow Comparison (on {both_valid_count} commonly valid pixels):")
            print(f"    Max absolute error: {max_abs_err:.6f} pixels")
            print(f"    Mean absolute error: {mean_abs_err:.6f} pixels")
            print(f"    RMSE: {rmse:.6f} pixels")
            print(f"    Max relative error: {max_relative_err:.4f}")

    # Print summary statistics
    print("\n" + "="*80)
    print("SUMMARY STATISTICS")
    print("="*80)

    if len(results['max_abs_error']) > 0:
        print(f"Files compared: {len(results['max_abs_error'])}")
        print(f"Total pixels compared: {sum(results['num_pixels_compared']):,}")

        print(f"\nMask Comparison:")
        print(f"  Mean mask agreement: {np.mean(results['mask_agreement'])*100:.2f}%")
        print(f"  Avg PNG valid pixels: {np.mean(results['mask_png_valid_count']):.0f}")
        print(f"  Avg NPZ valid pixels: {np.mean(results['mask_npz_valid_count']):.0f}")
        print(f"  Avg both valid pixels: {np.mean(results['mask_both_valid_count']):.0f}")

        print(f"\nFlow Absolute Error (pixels):")
        print(f"  Max across all files: {np.max(results['max_abs_error']):.6f}")
        print(f"  Mean of max errors: {np.mean(results['max_abs_error']):.6f}")
        print(f"  Mean of mean errors: {np.mean(results['mean_abs_error']):.6f}")
        print(f"  Mean RMSE: {np.mean(results['rmse']):.6f}")

        print(f"\nFlow Relative Error:")
        print(f"  Max across all files: {np.max(results['max_relative_error']):.4f}")
        print(f"  Mean of max errors: {np.mean(results['max_relative_error']):.4f}")

        # Determine consistency
        max_error = np.max(results['max_abs_error'])
        mean_error = np.mean(results['mean_abs_error'])
        mask_agreement = np.mean(results['mask_agreement'])

        print(f"\n{'='*80}")
        print("FLOW CONSISTENCY:")
        if max_error < 1e-3 and mean_error < 1e-4:
            print("  ✅ PNG and NPZ flows are CONSISTENT (errors < numerical precision)")
        elif max_error < 0.1 and mean_error < 0.01:
            print("  ✅ PNG and NPZ flows are VERY CLOSE (sub-pixel errors)")
        elif max_error < 1.0 and mean_error < 0.1:
            print("  ⚠️  PNG and NPZ flows have SMALL DIFFERENCES (may be acceptable)")
        else:
            print("  ❌ PNG and NPZ flows have SIGNIFICANT DIFFERENCES")

        print(f"\nMASK CONSISTENCY:")
        if mask_agreement > 0.99:
            print(f"  ✅ PNG and NPZ masks are HIGHLY CONSISTENT ({mask_agreement*100:.2f}% agreement)")
        elif mask_agreement > 0.95:
            print(f"  ✅ PNG and NPZ masks are CONSISTENT ({mask_agreement*100:.2f}% agreement)")
        elif mask_agreement > 0.90:
            print(f"  ⚠️  PNG and NPZ masks have MINOR DIFFERENCES ({mask_agreement*100:.2f}% agreement)")
        else:
            print(f"  ❌ PNG and NPZ masks have SIGNIFICANT DIFFERENCES ({mask_agreement*100:.2f}% agreement)")
    else:
        print("❌ No files were successfully compared!")

    return results


if __name__ == "__main__":
    # Define paths
    png_dir = "/data/tartanair/ModularNeighborhoodIntExt/Data_easy/ModularNeighborhoodIntExt/Data_easy/P008/flow_lcam_front"
    npz_dir = "/data/tartanair/ModularNeighborhoodIntExt/Data_easy/P008/flow_lcam_front"
    rgb_dir = "/data/tartanair/ModularNeighborhoodIntExt/Data_easy/P008/image_lcam_front"

    # Configuration
    VISUALIZE_RERUN = True  # Set to True to stream to rerun
    RERUN_ADDR = "rerun+http://100.89.23.40:9876/proxy"  # Rerun server address

    # Run comparison
    # When visualizing, we compare all files to show complete timeline
    # Set VISUALIZE_RERUN=False and num_samples=10 for quick text-only check
    results = compare_flow_sources(
        png_dir=png_dir,
        npz_dir=npz_dir,
        num_samples=None,  # Compare all files
        verbose=not VISUALIZE_RERUN,  # Disable verbose output when visualizing to reduce clutter
        visualize_rerun=VISUALIZE_RERUN,
        rerun_addr=RERUN_ADDR,
        rgb_dir=rgb_dir
    )
